-- RedefineTables
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_Character" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "name" TEXT NOT NULL,
    "race" TEXT NOT NULL,
    "classLevel" TEXT NOT NULL,
    "level" INTEGER NOT NULL DEFAULT 1,
    "alignment" TEXT NOT NULL DEFAULT 'N',
    "strength" INTEGER NOT NULL DEFAULT 10,
    "dexterity" INTEGER NOT NULL DEFAULT 10,
    "constitution" INTEGER NOT NULL DEFAULT 10,
    "intelligence" INTEGER NOT NULL DEFAULT 10,
    "wisdom" INTEGER NOT NULL DEFAULT 10,
    "charisma" INTEGER NOT NULL DEFAULT 10,
    "hitPointsMax" INTEGER NOT NULL DEFAULT 1,
    "hitPointsCurrent" INTEGER NOT NULL DEFAULT 1,
    "armorClass" INTEGER NOT NULL DEFAULT 10,
    "baseAttackBonus" INTEGER NOT NULL DEFAULT 0,
    "initiative" INTEGER NOT NULL DEFAULT 0,
    "speed" INTEGER NOT NULL DEFAULT 30,
    "saveFort" INTEGER NOT NULL DEFAULT 0,
    "saveRef" INTEGER NOT NULL DEFAULT 0,
    "saveWill" INTEGER NOT NULL DEFAULT 0,
    "pspMax" INTEGER NOT NULL DEFAULT 0,
    "pspCurrent" INTEGER NOT NULL DEFAULT 0,
    "skills" TEXT NOT NULL DEFAULT '[]',
    "feats" TEXT NOT NULL DEFAULT '[]',
    "powers" TEXT NOT NULL DEFAULT '[]',
    "equipment" TEXT NOT NULL DEFAULT '[]',
    "spells" TEXT NOT NULL DEFAULT '[]',
    "spellSlots" TEXT NOT NULL DEFAULT '[]',
    "currencyCp" INTEGER NOT NULL DEFAULT 0,
    "currencySp" INTEGER NOT NULL DEFAULT 0,
    "currencyGp" INTEGER NOT NULL DEFAULT 0,
    "currencyBits" INTEGER NOT NULL DEFAULT 0,
    "experiencePoints" INTEGER NOT NULL DEFAULT 0,
    "acArmor" INTEGER NOT NULL DEFAULT 0,
    "acShield" INTEGER NOT NULL DEFAULT 0,
    "acNatural" INTEGER NOT NULL DEFAULT 0,
    "acDeflection" INTEGER NOT NULL DEFAULT 0,
    "acMisc" INTEGER NOT NULL DEFAULT 0,
    "acSizeMod" INTEGER NOT NULL DEFAULT 0,
    "gender" TEXT NOT NULL DEFAULT '',
    "age" TEXT NOT NULL DEFAULT '',
    "height" TEXT NOT NULL DEFAULT '',
    "weight" TEXT NOT NULL DEFAULT '',
    "deity" TEXT NOT NULL DEFAULT '',
    "appearance" TEXT NOT NULL DEFAULT '',
    "personality" TEXT NOT NULL DEFAULT '',
    "conditions" TEXT NOT NULL DEFAULT '[]',
    "classLevels" TEXT NOT NULL DEFAULT '[]',
    "notes" TEXT NOT NULL DEFAULT '',
    "userId" TEXT NOT NULL,
    "campaignId" TEXT NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "Character_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "Character_campaignId_fkey" FOREIGN KEY ("campaignId") REFERENCES "Campaign" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
INSERT INTO "new_Character" ("acArmor", "acDeflection", "acMisc", "acNatural", "acShield", "acSizeMod", "age", "alignment", "appearance", "armorClass", "baseAttackBonus", "campaignId", "charisma", "classLevel", "conditions", "constitution", "createdAt", "currencyBits", "currencyCp", "currencyGp", "currencySp", "deity", "dexterity", "equipment", "experiencePoints", "feats", "gender", "height", "hitPointsCurrent", "hitPointsMax", "id", "initiative", "intelligence", "level", "name", "notes", "personality", "powers", "pspCurrent", "pspMax", "race", "saveFort", "saveRef", "saveWill", "skills", "speed", "spellSlots", "spells", "strength", "updatedAt", "userId", "weight", "wisdom") SELECT "acArmor", "acDeflection", "acMisc", "acNatural", "acShield", "acSizeMod", "age", "alignment", "appearance", "armorClass", "baseAttackBonus", "campaignId", "charisma", "classLevel", "conditions", "constitution", "createdAt", "currencyBits", "currencyCp", "currencyGp", "currencySp", "deity", "dexterity", "equipment", "experiencePoints", "feats", "gender", "height", "hitPointsCurrent", "hitPointsMax", "id", "initiative", "intelligence", "level", "name", "notes", "personality", "powers", "pspCurrent", "pspMax", "race", "saveFort", "saveRef", "saveWill", "skills", "speed", "spellSlots", "spells", "strength", "updatedAt", "userId", "weight", "wisdom" FROM "Character";
DROP TABLE "Character";
ALTER TABLE "new_Character" RENAME TO "Character";
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;
