export interface Skill3_5E {
    name: string;
    ability: string;
    trainedOnly: boolean;
}

export const SKILLS_3_5E: Skill3_5E[] = [
    { name: 'Appraise', ability: 'INT', trainedOnly: false },
    { name: 'Balance', ability: 'DEX', trainedOnly: false },
    { name: 'Bluff', ability: 'CHA', trainedOnly: false },
    { name: 'Climb', ability: 'STR', trainedOnly: false },
    { name: 'Concentration', ability: 'CON', trainedOnly: false },
    { name: 'Craft', ability: 'INT', trainedOnly: false },
    { name: 'Decipher Script', ability: 'INT', trainedOnly: true },
    { name: 'Diplomacy', ability: 'CHA', trainedOnly: false },
    { name: 'Disable Device', ability: 'INT', trainedOnly: true },
    { name: 'Disguise', ability: 'CHA', trainedOnly: false },
    { name: 'Escape Artist', ability: 'DEX', trainedOnly: false },
    { name: 'Forgery', ability: 'INT', trainedOnly: false },
    { name: 'Gather Information', ability: 'CHA', trainedOnly: false },
    { name: 'Handle Animal', ability: 'CHA', trainedOnly: true },
    { name: 'Heal', ability: 'WIS', trainedOnly: false },
    { name: 'Hide', ability: 'DEX', trainedOnly: false },
    { name: 'Intimidate', ability: 'CHA', trainedOnly: false },
    { name: 'Jump', ability: 'STR', trainedOnly: false },
    { name: 'Knowledge (Arcana)', ability: 'INT', trainedOnly: true },
    { name: 'Knowledge (Local)', ability: 'INT', trainedOnly: true },
    { name: 'Knowledge (Nature)', ability: 'INT', trainedOnly: true },
    { name: 'Knowledge (Psionics)', ability: 'INT', trainedOnly: true },
    { name: 'Knowledge (Religion)', ability: 'INT', trainedOnly: true },
    { name: 'Knowledge (Warcraft)', ability: 'INT', trainedOnly: true },
    { name: 'Listen', ability: 'WIS', trainedOnly: false },
    { name: 'Move Silently', ability: 'DEX', trainedOnly: false },
    { name: 'Open Lock', ability: 'DEX', trainedOnly: true },
    { name: 'Perform', ability: 'CHA', trainedOnly: false },
    { name: 'Profession', ability: 'WIS', trainedOnly: true },
    { name: 'Psicraft', ability: 'INT', trainedOnly: true },
    { name: 'Ride', ability: 'DEX', trainedOnly: false },
    { name: 'Search', ability: 'INT', trainedOnly: false },
    { name: 'Sense Motive', ability: 'WIS', trainedOnly: false },
    { name: 'Sleight of Hand', ability: 'DEX', trainedOnly: true },
    { name: 'Spellcraft', ability: 'INT', trainedOnly: true },
    { name: 'Spot', ability: 'WIS', trainedOnly: false },
    { name: 'Survival', ability: 'WIS', trainedOnly: false },
    { name: 'Swim', ability: 'STR', trainedOnly: false },
    { name: 'Tumble', ability: 'DEX', trainedOnly: true },
    { name: 'Use Magic Device', ability: 'CHA', trainedOnly: true },
    { name: 'Use Rope', ability: 'DEX', trainedOnly: false },
];
